### ISSUE TITLE
xcode 6.0.1 support?

### ISSUE THREAD

**Issue by VVes** [mitchellallison/WarningLights#4]
Project built and installed where your documentation said it would, but the menu item doesn't show up under "Product".  Any idea where to start debugging?

**Comment by DoctorG** [comment]
Can you please update this for XCODE 6.1 and update the pod spec.  

Thanks!

**Comment by mitchellallison** [comment]
As of version [1.2](https://github.com/mitchellallison/WarningLights/releases/tag/1.2), the above issue should now be fixed. Please report any bugs you encounter!
